[doc] Fix install commands to use full path or URL

diff --git a/.github/workflows/exist.yml b/.github/workflows/exist.yml
--- a/.github/workflows/exist.yml
+++ b/.github/workflows/exist.yml
@@ -72,30 +72,45 @@ jobs:
           echo "$result" | grep -q "request module loaded" || (echo "FAIL: request module not loaded" && exit 1)
 
       # Smoke tests: verify functions work
-      - name: Test exrequest:method returns GET
+      - name: Test exrequest:method returns POST
         run: |
-          result=$(curl -sf -u admin: \
-            'http://localhost:8080/exist/rest/db?_query=import%20module%20namespace%20exrequest%20%3D%20%22http%3A%2F%2Fexquery.org%2Fns%2Frequest%22%3B%20exrequest%3Amethod()&_wrap=no')
+          result=$(curl -s -u admin: -H "Content-Type: application/xml" --data '
+          <query xmlns="http://exist.sourceforge.net/NS/exist">
+            <text><![CDATA[
+              import module namespace exrequest = "http://exquery.org/ns/request";
+              exrequest:method()
+            ]]></text>
+          </query>' "http://localhost:8080/exist/rest/db")
           echo "$result"
-          echo "$result" | grep -q "GET" || (echo "FAIL: expected GET" && exit 1)
+          echo "$result" | grep -q "POST" || (echo "FAIL: expected POST" && exit 1)
 
       - name: Test exrequest:scheme returns http
         run: |
-          result=$(curl -sf -u admin: \
-            'http://localhost:8080/exist/rest/db?_query=import%20module%20namespace%20exrequest%20%3D%20%22http%3A%2F%2Fexquery.org%2Fns%2Frequest%22%3B%20exrequest%3Ascheme()&_wrap=no')
+          result=$(curl -s -u admin: -H "Content-Type: application/xml" --data '
+          <query xmlns="http://exist.sourceforge.net/NS/exist">
+            <text><![CDATA[
+              import module namespace exrequest = "http://exquery.org/ns/request";
+              exrequest:scheme()
+            ]]></text>
+          </query>' "http://localhost:8080/exist/rest/db")
           echo "$result"
           echo "$result" | grep -q "http" || (echo "FAIL: expected http" && exit 1)
 
       - name: Test exrequest:parameter with default value
         run: |
-          result=$(curl -sf -u admin: \
-            'http://localhost:8080/exist/rest/db?_query=import%20module%20namespace%20exrequest%20%3D%20%22http%3A%2F%2Fexquery.org%2Fns%2Frequest%22%3B%20exrequest%3Aparameter(%22missing%22%2C%20%22fallback%22)&_wrap=no')
+          result=$(curl -s -u admin: -H "Content-Type: application/xml" --data '
+          <query xmlns="http://exist.sourceforge.net/NS/exist">
+            <text><![CDATA[
+              import module namespace exrequest = "http://exquery.org/ns/request";
+              exrequest:parameter("missing", "fallback")
+            ]]></text>
+          </query>' "http://localhost:8080/exist/rest/db")
           echo "$result"
           echo "$result" | grep -q "fallback" || (echo "FAIL: expected fallback" && exit 1)
 
       - name: Test exrequest:header-names returns non-empty sequence
         run: |
-          result=$(curl -sf -u admin: -H "Content-Type: application/xml" --data '
+          result=$(curl -s -u admin: -H "Content-Type: application/xml" --data '
           <query xmlns="http://exist.sourceforge.net/NS/exist">
             <text><![CDATA[
               import module namespace exrequest = "http://exquery.org/ns/request";
@@ -107,7 +122,7 @@ jobs:
 
       - name: Test exrequest:set-attribute and exrequest:attribute round-trip
         run: |
-          result=$(curl -sf -u admin: -H "Content-Type: application/xml" --data '
+          result=$(curl -s -u admin: -H "Content-Type: application/xml" --data '
           <query xmlns="http://exist.sourceforge.net/NS/exist">
             <text><![CDATA[
               import module namespace exrequest = "http://exquery.org/ns/request";
@@ -120,7 +135,7 @@ jobs:
 
       - name: Test exrequest:parameter-map returns a map
         run: |
-          result=$(curl -sf -u admin: -H "Content-Type: application/xml" --data '
+          result=$(curl -s -u admin: -H "Content-Type: application/xml" --data '
           <query xmlns="http://exist.sourceforge.net/NS/exist">
             <text><![CDATA[
               import module namespace exrequest = "http://exquery.org/ns/request";
